[package]
name = "rchat_server"
version = "0.1.0"
authors = ["iyyel <i@iyyel.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.8.1"